spring:
  application:
    name: alipay-app

















alipay:
  appId: 9021000136625098
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCnIOaJINZRiyy+H2zYhceXnHA4Gjo64J8tqSvvynBjJgsKaiudE+Kp5uKLSwUPTscEloXRbvKaJtWNowQBRLSUG7QZU67b+RYULM1fgqiBU+NTjKXb5yI1MJNvfIF8831SMtFuM/xBbnPbaZP9NfBssXmG2R4LD9Tgw+Ejtma9HJHU4Lid4Pz9WY/85NXR/Y0Ak/d2vHrdjLyHseXT4ueLd8OhbFA+dBOk87wpMkL8ZGPEjYSgexuwW/avKiSjwBlt/knKK6ba//SESJ4qkpT042YNrGytSdZFLGhanJgi2dIGg5liEBM2yKPcceIf9V2uiDT5wMOjQNEEEx5jcmjnAgMBAAECggEAczcfNtHIbhbAFaGca/huDHrwcfzCv+wyUEwb2gd5SyDi458lyff3fqGI8/YX2uG4GdWbEzKlVNgIyMfk7urqgmBG3F7wYP1q1yW7v2hXujCWuvZvMRY6YujF+0meCwHhF1WpQ4vbD1CR1mUGfL0+re/7k5cCOyYC36CqCPCqCxwRoWxqLJDXFxRqLSt5QOyKnYAQvc30g6BoFiRRszE4ekZ+K4BiWwO5LsC9ABIrQS06Yk6jX/APjsppKThnQcv7vHgiykZiOomhq6EyGo647LwrmjtFnRSEgpEGES96htPP49qjcMOlZiWM2IPCC5uG2XwZZ99VvhPXi8jHCQLPAQKBgQD1VWJXyjVRxx1UPepUYy/fHZrMUO7xGFRjGQfNgRT09pdGK92tU6Kl81k/QKAf6AHdjegOWeHeYQNIVHpcmLACN0FzAGFlD7A6TxK65E2Z/Mn/lWEpolZ9LfBC/ovVgXLi8tJ0v6yLBatfvMkENjel8hP3nKvtUQnh5NHwzh9PYQKBgQCuZRPVNJ0qS1ydSWgIA8UGHAdA32nBEFOMgSgc2/S02GD5j5Wstj8UhBqoyHtocBths/Rqv1Zy6z9AV0cuIte24qydekwxJyZ/rhDvJvy6Q5EurZAYluTsk5DdHTT6/Cln7ZP0aCUrKjrq4Vm03tpf+NEPCWX9tGmgUYA3QEaFRwKBgQDvkJ0jlPVUEdd196/nD6Qjf0k10qJBE7zzt/GCn1XTjyhRAWzKYC0nV+YCehziiy+nJXdA7Ew/VwRZkQSbfw4AW+yxW+G/Sf6QMb7ceSu9/rdRuJDUkw1Z144SHXZ22p1ROESCdNkMOFEMf9DbKAZXKXiOBpNsfgHkcAkB2IWCgQKBgB4uZAZL+r8tF7Qo1hY9AMYT57V0dMry1mLEn3qPHoSFxhKqpM6lI7mbOznmqGTksfhwumYXAxEUYXfzIuB7KzX9eL4wQitniSQjrc6VwrtBokifxQZcZvYCe9moili9dzUDSs3LkFMuFdA8e9fvkX92gkfF6p7DsFwMftIRD6NVAoGANXUXi3lh59+95Ljwxq2l0mAq5ObLD05PjE+ivo6/Bgah7+0OOK1v0udgWysFVu3tI0QnmIkkQ69NM/DbeCE7+1ksLtPaACSpIvCx2GyFMfdlhSuYJ4f5ABCdgG4rLsdeqJ6JJzw+MH37hziQKVIy8nj0McdreohTeCKFuM/HFDw=
  publiceKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgiFZXm6LEPPM2G57o+RTgs/VrdGAEDTHIvqhZY42ZWclX1gccAE3hVCjq0VvgpGbDEa8ePxCYrclSdgi4lelsGDkCbRNARZ3ENTrmf6wfZpE56HzhyprxIkn089xrAY1cIhL0KhvUHtp5rKE7xiAfJsuZf6d6wKAehqi/D1OM4Nu1uPzKP0sEfaFg5V88EU2qhV8mO0OL0w8sAVB6CXnZ5gdFzc6lg23GH/1PpAK+H4ruwalMAh8wFe96Y5XDLUo6IBjvLZdyLSFrgfYZnXv7HM/HXpGW3K+QldTBBzAiGAHcgBfebSnpQunBtRkjvfK2NhPeqHu7Ca17fUcgUOgGwIDAQAB
  notifyUrl: http://h5weixin.w1.luyouxia.net/api/alipay/notify
  gatewayHost: openapi-sandbox.dl.alipaydev.com
